### ISSUE TITLE
Diels example not working

### ISSUE THREAD

**Issue by sbecuwe** [ZimmermanGroup/molecularGSM#19]
Hello

I compiled the tribits branch using CMake 3.11.1 and Intel 2019 compilers and MKL (`cmake -DCMAKE_C_COMPILER=icc -DCMAKE_CXX_COMPILER=icpc -DGSM_ENABLE_GAUSSIAN=1`). After applying patches as described in #18 , I got an executable for Gaussian 16. Running the example in TEST/diels (`gsm.gaussian.exe 1 10`), I got following output: [diels-output.txt](https://github.com/ZimmermanGroup/molecularGSM/files/4912357/diels-output.txt). Something went wrong, but I don't have a clue.

Thanks!
Stefan

**Comment by marcog2020460** [comment]
hello Stefan, 

I followed your instructions, and created an executable.
But when I run the executable produces a core (segmentation default)
Can you please help me

**Comment by perkinsns** [comment]
Hi Stephan,

Can you give me some more information? I was unable to reproduce your error. Are you using the tribits branch of the code? If not, try compiling using that branch and let me know how it goes. We have also recently updated the code so if you are already using the tribits branch, try using the updated code and see if that helps anything.

Nikki

**Comment by joshkamm** [comment]
closing as stale
