### ISSUE TITLE
Energy unit in stringfile.xyz0001

### ISSUE THREAD

**Issue by shaoqx** [ZimmermanGroup/molecularGSM#22]
Dear GSM team,

I want to ask about the energy unit in the final stringfile. Had a hard time finding it in the document. Just want to be sure. Thank you!

All the Best,
Qianzhen

**Comment by perkinsns** [comment]
Hi Qianzhen,

Under the "Analyzing Output" section of the wiki, it states that the energies given are in kcal/mol.
"E: 2.7 Transition state energy in kcal/mol"

Nikki
