### ISSUE TITLE
CMake requires Doxygen installed

### ISSUE THREAD

**Issue by shaoqx** [ZimmermanGroup/molecularGSM#27]
I tried to compile GSM with CMake and I got this error:
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Configuring incomplete, errors occurred!

But it seems Doxygen is a software that generates documents. Do we really need it for building GSM?

**Comment by shaoqx** [comment]
And I cannot install Doxygen because I'm trying to install it on a cluster of my school and I do not have the sudo permission.

**Comment by perkinsns** [comment]
Hello!

Try commenting out this last line in CMakeLists.txt of the top directory.
"ADD_SUBDIRECTORY(docs)"

**Comment by peggjt** [comment]
I also got this error followed by:
```
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 

Getting information for all enabled TPLs ...


Setting up testing support ...


Configuring individual enabled GSM packages ...

Processing enabled package: gsm (Libs)
CMake Error at /usr/local/Cellar/cmake/3.22.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find MKL (missing: MKL_LIBRARIES MKL_INCLUDE_DIRS
  MKL_INTERFACE_LIBRARY MKL_SEQUENTIAL_LAYER_LIBRARY MKL_CORE_LIBRARY)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.22.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindMKL.cmake:135 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  GSM/CMakeLists.txt:69 (find_package)


-- Configuring incomplete, errors occurred!
```
The same error occurred after commenting out `"ADD_SUBDIRECTORY(docs)"`

**Comment by perkinsns** [comment]
Hi James,

So sorry for my delayed response.

Did you try commenting out this last line in CMakeLists.txt of the top
directory.
"ADD_SUBDIRECTORY(docs)"?

Let me know and I can help you further.

Nikki

**Comment by duykhoidang** [comment]
Build has been updated. Try with new master branch.
