### ISSUE TITLE
Cmake Error

### ISSUE THREAD

**Issue by Saikat248** [ZimmermanGroup/molecularGSM#4]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
MKL_INCLUDE_DIR (ADVANCED)
used as include directory in directory /home/anoop/molecularGSM/GSM
used as include directory in directory /home/anoop/molecularGSM/GSM
used as include directory in directory /home/anoop/molecularGSM/GSM
used as include directory in directory /home/anoop/molecularGSM/GSM
used as include directory in directory /home/anoop/molecularGSM/GSM
used as include directory in directory /home/anoop/molecularGSM/GSM
used as include directory in directory /home/anoop/molecularGSM/GSM
used as include directory in directory /home/anoop/molecularGSM/GSM
used as include directory in directory /home/anoop/molecularGSM/GSM
used as include directory in directory /home/anoop/molecularGSM/GSM

-- Configuring incomplete, errors occurred!

-->

**Comment by mina-jafari** [comment]
GSM needs MKL library to compile. Also, see this link:
https://github.com/andersx/molecularGSM/commit/ce1f45671282dcf9615969265b6d38854129b24c
