### ISSUE TITLE
Templates for DE-GSM

### ISSUE THREAD

**Issue by mbuche** [ZimmermanGroup/molecularGSM#5]
I have GSM installed was was going through

[https://github.com/ZimmermanGroup/molecularGSM/wiki](url)

when I got to the DE_GSM template directory at

[/export/zimmerman/ipendlet/GSM_Files/GSM_template](url)

which I think is on your lab's cluster, not in the installation directory. Where can I find a directory like this to learn how to form GSM input scripts?

**Comment by mina-jafari** [comment]
Hi Michael,

Thank you for pointing out this problem.

You can find a couple of examples in this link:
https://github.com/ZimmermanGroup/molecularGSM/tree/master/TEST

This is an example with QChem:
https://github.com/ZimmermanGroup/molecularGSM/tree/master/TEST/dielsAlder/qchem/de-gsm

We will update the tutorial accordingly by the end of summer.

**Comment by mbuche** [comment]
Okay, thank you for your help. I see the Dies-Alder reaction example. How should the execution line look for script submission? I see that inpfileq contains information about the GSM settings, and gscreate creates a qchem script qcin based on qstart, qend, and molecule (I assume I must go to my qchem scratch to put in the xyz coordinates of my structure as "molecule"?), but I do not see how to form the submission line of the form

./path/gsm.qchem.exe ...

using these files, or how to include both the reactant and product structures (is this done in "molecule"?)

**Comment by mina-jafari** [comment]
Ah, I see, critical information is missing.
./gfstringq.exe 1 4 > scratch/paragsm1
1: job number, referring to the numbering of initial##.xyz file.
4: number of cpu's used, using more than 4 wouldn't speed up the calculation.

If you're using DE-GSM, the format of the inital##.xyz (where you input chemical structures) should be like this:
https://github.com/ZimmermanGroup/molecularGSM/blob/master/TEST/dielsAlder/qchem/de-gsm/scratch/initial0001.xyz

This explains how to do so:
https://github.com/ZimmermanGroup/molecularGSM/wiki#setting-up-the-de-gsm

And if you want QChem to write optimized geometry in Cartesians, add
molden_format true
to your QChem optimization's preamble.

**Comment by mina-jafari** [comment]
stringfile.xyz0001 is the one you want. You can ignore all the files generated in the scratch directory.

You can view stringfile.xyz0001 file with a software like Molden or VMD to see progression of the reaction.

Happy to hear that, hope it works smoothly now that you've set it up.

**Comment by mbuche** [comment]
Thank you so much!!
