### ISSUE TITLE
Davidson calculations

### ISSUE THREAD

**Issue by mbuche** [ZimmermanGroup/molecularGSM#7]
It seems from the paragsm1 file that the GSM program finished by running a Davidson diagonalization of the lowest (3?) eigenvalues of the transition state Hessian to verify that there is only one negative eigenvalue. Is this just a double-check, or is this step important (if more or less than one negative eigenvalue was found, would it go back to changing the string and TS)?

**Comment by mbuche** [comment]
Okay I see now. I will follow up with a question about restarting a calculation: I have to restart my calculation periodically due to runtime constraints, saving a restart0001.xyz string file. It seems like it will go back and repeat calculations that it already had in the last run, maybe since it only uses a set of structures to restart. For example, I had a run that made it to the Davidson method portion at the end before timing out, and upon restarting the calculation began back at the climbing image search. Is there a way to restart without completing these processes again?

**Comment by mina-jafari** [comment]
You can turn off Davidson in the code and recompile it, you actually don't need it.
In the gstring.cpp file, set the following to zero:
#define USE_DAVID 0

**Comment by mbuche** [comment]
Got it, thank you!
